apiVersion: apps/v1
kind: Deployment
metadata:
  name: blotter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: blotter
  template:
    metadata:
      labels:
        component: blotter
    spec:
      containers:
        - name: blotter
          image: reactivetrader/servers:90
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            - name: EVENTSTORE_HOST
              value: eventstore
            - name: EVENTSTORE_PORT
              value: '1113'
          command:
            [
              'sh',
              '-c',
              'dotnet ./Adaptive.ReactiveTrader.Server.Blotter.dll config.prod.json',
            ]
