apiVersion: apps/v1
kind: Deployment
metadata:
  name: referencedataread-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: referencedataread
  template:
    metadata:
      labels:
        component: referencedataread
    spec:
      containers:
        - name: referencedataread
          image: reactivetradercloud/servers:${BUILD_VERSION}
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            - name: EVENTSTORE_HOST
              value: eventstore
            - name: EVENTSTORE_PORT
              value: '1113'
          command:
            [
              'sh',
              '-c',
              'dotnet ./Adaptive.ReactiveTrader.Server.ReferenceDataRead.dll config.prod.json',
            ]
