apiVersion: v1
kind: ReplicationController
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name: "__SERVICE__"
    major: "__MAJOR__"
    minor: "__MINOR__"
    build: "__BUILD__"
spec:
  replicas: 1
  selector:
    name: "__SERVICE__"
    major: "__MAJOR__"
    minor: "__MINOR__"
    build: "__BUILD__"
  template:
    metadata:
      labels:
        name: "__SERVICE__"
        major: "__MAJOR__"
        minor: "__MINOR__"
        build: "__BUILD__"
    spec:
      containers:
      - name: "__SERVICE__"
        image: "__DOCKERIMAGE__"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2113
            name: "eventstore"
          - containerPort: 1113
            name: "eventstore-tcp"
