apiVersion: v1
kind: Service
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name: "__SERVICE__"
    major: "__MAJOR__"
    public: "true"
spec:
  selector:
    name: "__SERVICE__"
    major: "__MAJOR__"
  ports:
  - port: 2113
    targetPort: 2113
    name: "http"
  - port: 1113
    targetPort: 1113
    name: "stream"
