sudo: required

services:
  - docker

cache:
  directories:
    - deploy/docker/build/servers/dotnetcache
    - deploy/docker/build/web/.npm

before_script:
  - TRAVIS_BUILD_NUMBER=$(($TRAVIS_BUILD_NUMBER+650)) # adjust build number to match CircleCi
  - docker info
  - cd deploy/e2e 
  - chmod 755 ensurePermissions
  - ./ensurePermissions
  - ./buildContainers $TRAVIS_BUILD_NUMBER
  - ./runContainers $TRAVIS_BUILD_NUMBER
  - cd ../..

script:
  - docker ps
  - for i in {1..10}; do curl http://localhost:2113/web/index.html && break; sleep 1; if [[ $i == 10 ]];then false;fi; done
  - . ./deploy/config && docker run -a STDOUT --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dotnet test --configuration Release Adaptive.ReactiveTrader.Server.IntegrationTests"
