sudo: required

services:
  - docker

cache:
  directories:
    - deploy/docker/build/servers/dnxcache
    - deploy/docker/build/web/.npm

before_script:
  - docker info
  - cd deploy/travisCi 
  - chmod 755 ensurePermissions
  - ./ensurePermissions
  - ./buildContainers
  - ./runContainers
  - cd ../..

script:
  - docker ps
  # multiple attempt to test Eventstore is up
  - for i in {1..10}; do curl http://localhost:2113/web/index.html && break; sleep 1; if [[ $i == 10 ]];then false;fi; done
  # test
  - . ./deploy/config && docker run -a STDOUT --net=host $serversContainer:$vMajor.$vMinor.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.IntegrationTests test -parallel none"
