apiVersion: v1
kind: Service
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name:   "__SERVICE__"
    major:  "__MAJOR__"
    public: "true"
spec:
  selector:
    name:  "__SERVICE__"
    major: "__MAJOR__"
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 8080
    targetPort: 8080
    name: "ws"
