apiVersion: v1
kind: Service
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name: "__SERVICE__"
    major: "__MAJOR__"
    minor: "__MINOR__"
spec:
  selector:
    name: "__SERVICE__"
    major: "__MAJOR__"
    minor: "__MINOR__"
  ports:
  - port: __SERVICEPORT__
    targetPort: __CONTAINERPORT__
  type: "LoadBalancer"
