apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eventstore
  template:
    metadata:
      labels:
        component: eventstore
    spec:
      containers:
        - name: eventstore
          image: ${DOCKER_USER}/eventstore:${BUILD_VERSION}
          ports:
            - containerPort: 1113
            - containerPort: 2113
          resources:
            requests:
              memory: "256Mi"
              cpu: "80m"
          volumeMounts:
            - mountPath: /db
              name: eventstore-data
      volumes:
        - name: eventstore-data
          persistentVolumeClaim:
            claimName: eventstore-volume

