apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: rt-ingress-demo
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: reactive-trader-issuer
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"

spec:
  tls:
  - hosts:
    - reactivetrader.com
    - www.reactivetrader.com
    - classic.reactivetrader.com
    - web-demo.adaptivecluster.com
    secretName: reactive-trader-tls

  rules:
  - host: www.reactivetrader.com
    http:
      paths:
      - path: /ws
        backend:
          serviceName: broker
          servicePort: 15674

      - path: /storybook
        backend:
          serviceName: storybook
          servicePort: 80

      - path: /styleguide
        backend:
          serviceName: styleguide
          servicePort: 80

      - path: /
        backend:
          serviceName: new-client
          servicePort: 3000

  - host: web-demo.adaptivecluster.com
    http:
      paths:
      - path: /ws
        backend:
          serviceName: broker
          servicePort: 15674

      - path: /storybook
        backend:
          serviceName: storybook
          servicePort: 80

      - path: /styleguide
        backend:
          serviceName: styleguide
          servicePort: 80

      - path: /
        backend:
          serviceName: client
          servicePort: 3000

  - host: classic.reactivetrader.com
    http:
      paths:
      - path: /ws
        backend:
          serviceName: broker
          servicePort: 15674

      - path: /storybook
        backend:
          serviceName: storybook
          servicePort: 80

      - path: /styleguide
        backend:
          serviceName: styleguide
          servicePort: 80

      - path: /
        backend:
          serviceName: client
          servicePort: 3000
