apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: rt-ingress-dev
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: reactive-trader-issuer
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-alias: "web-dev.adaptivecluster.com"

spec:
  tls:
  - hosts:
    - dev.reactivetrader.com
    - web-dev.adaptivecluster.com
    secretName: reactive-trader-tls

  rules:
  - host: dev.reactivetrader.com
    http:
      paths:
      - path: /ws
        backend:
          serviceName: broker
          servicePort: 15674

      - path: /storybook
        backend:
          serviceName: storybook
          servicePort: 80

      - path: /styleguide
        backend:
          serviceName: styleguide
          servicePort: 80

      - path: /
        backend:
          serviceName: client
          servicePort: 3000
