apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-ui-v3
  labels:
    k8s-app: kube-ui
spec:
  replicas: 1
  selector:
    k8s-app: kube-ui
  template:
    metadata:
      labels:
        k8s-app: kube-ui
    spec:
      containers:
      - name: kube-ui
        image: gcr.io/google_containers/kube-ui:v3
        ports:
        - containerPort: 8080
