apiVersion: v1
kind: Service
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name: "__SERVICE__"
    major: "__MAJOR__"
    public: "true"
spec:
  selector:
    name: "__SERVICE__"
    major: "__MAJOR__"
  ports:
  - port: 8000
    targetPort: 8000
    name: "broker"
