name: Scheduled E2E
on:
  schedule:
    - cron: "55 8 * * *"

defaults:
  run:
    working-directory: .

jobs:
  e2e:
    name: End-to-end smoke test against RT Prod

    runs-on: ubuntu-20.04

    if: github.repository_owner == 'AdaptiveConsulting'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        env:
          E2E_RTC_WEB_ROOT_URL: https://web.prod.reactivetrader.com
        run: |
          npm run e2e:web:smoke
